#-------------------------- BASE INFORMATION --------------------------#
name: rentool
description: "Mobile application for searching and renting equipment and tools for home repair and construction."

publish_to: 'none' 
version: 0.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


#-------------------------- PRODUCTION PACKAGES --------------------------#
dependencies:
  flutter:
    sdk: flutter
  
  # Utility
  flutter_native_splash: ^2.4.0

  # Icons
  cupertino_icons: ^1.0.6

#-------------------------- DEVELOPMENT PACKAGES --------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

#-------------------------- LOCAL ASSETS --------------------------#
# assets:
#   - assets/logos/
#   - assets/icons/
#   - assets/images/

#-------------------------- LOCAL FONTS --------------------------#
fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat/static/Montserrat-Thin.ttf
      - weight: 100
      - asset: assets/fonts/Montserrat/static/Montserrat-ThinItalic.ttf
      - weight: 100
      - style: italic
      - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf
      - weight: 200
      - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf
      - weight: 200
      - style: italic
      - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
      - weight: 300
      - asset: assets/fonts/Montserrat/static/Montserrat-LightItalic.ttf
      - weight: 300
      - style: italic
      - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
      - weight: 400
      - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
      - weight: 500
      - asset: assets/fonts/Montserrat/static/Montserrat-MediumItalic.ttf
      - weight: 500
      - style: italic
      - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
      - weight: 600
      - asset: assets/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf
      - weight: 600
      - style: italic
      - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
      - weight: 700
      - asset: assets/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
      - weight: 700
      - style: italic
      - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf
      - weight: 800
      - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf
      - weight: 800
      - style: italic
      - asset: assets/fonts/Montserrat/static/Montserrat-Black.ttf
      - weight: 900
      - asset: assets/fonts/Montserrat/static/Montserrat-BlackItalic.ttf
      - weight: 900
      - style: italic
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
