#-------------------------- BASE INFORMATION --------------------------#
name: rentool
description: "Mobile application for searching and renting equipment and tools for home repair and construction."

publish_to: 'none' 
version: 0.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


#-------------------------- PRODUCTION PACKAGES --------------------------#
dependencies:
  flutter:
    sdk: flutter
  
  # Utility
  flutter_native_splash: ^2.4.0
  auto_route: ^8.1.0
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  meta: ^1.11.0
  bloc: ^8.1.4
  uuid: ^4.4.0
  table_calendar: ^3.1.1
  intl: ^0.19.0

  
  # Icons
  cupertino_icons: ^1.0.8


#-------------------------- DEVELOPMENT PACKAGES --------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  auto_route_generator: ^8.0.0
  flutter_lints: ^3.0.2
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

#-------------------------- LOCAL ASSETS --------------------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/tests/
    - .env
#-------------------------- LOCAL FONTS --------------------------#
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Thin.ttf
        - weight: 100
        - asset: assets/fonts/Montserrat/static/Montserrat-ThinItalic.ttf
        - weight: 100
        - style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf
        - weight: 200
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf
        - weight: 200
        - style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
        - weight: 300
        - asset: assets/fonts/Montserrat/static/Montserrat-LightItalic.ttf
        - weight: 300
        - style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Montserrat/static/Montserrat-RegularItalic.ttf
        - weight: 400
        - style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Montserrat/static/Montserrat-MediumItalic.ttf
        - weight: 500
        - style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf
        - weight: 600
        - style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
        - weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
        - weight: 700
        - style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf
        - weight: 800
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf
        - weight: 800
        - style: italic
        - asset: assets/fonts/Montserrat/static/Montserrat-Black.ttf
        - weight: 900
        - asset: assets/fonts/Montserrat/static/Montserrat-BlackItalic.ttf
        - weight: 900
        - style: italic